# Generated by Django 5.1.4 on 2024-12-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agentmvp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chatbot',
            new_name='Agent',
        ),
        migrations.RenameIndex(
            model_name='agent',
            new_name='agentmvp_ag_custome_21db7e_idx',
            old_name='agentmvp_ch_custome_a1fad1_idx',
        ),
        migrations.RenameIndex(
            model_name='agent',
            new_name='agentmvp_ag_website_83dd1e_idx',
            old_name='agentmvp_ch_website_1c1c9e_idx',
        ),
    ]
