# Generated by Django 5.1.4 on 2024-12-06 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agentmvp', '0002_rename_chatbot_agent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='chatbot',
            new_name='Agent',
        ),
    ]
