# Generated by Django 5.1.4 on 2024-12-09 13:57

import agentmvp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentmvp', '0003_rename_chatbot_chat_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='status',
        ),
        migrations.AddField(
            model_name='agent',
            name='business_docx',
            field=models.FileField(blank=True, null=True, upload_to='business_docs/', validators=[agentmvp.models.validate_file_extension]),
        ),
    ]
