# Generated by Django 5.1.4 on 2024-12-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agentmvp', '0004_remove_agent_status_agent_business_docx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='sales_techniques',
        ),
    ]
