# Generated by Django 5.1.4 on 2024-12-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentmvp', '0008_remove_agent_business_docx_agentdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='Agents_logo/'),
        ),
    ]
