# Generated by Django 5.1.4 on 2024-12-18 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentmvp', '0009_agent_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salestechnique',
            name='document',
        ),
        migrations.CreateModel(
            name='SalesTechniquesDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='sales_techniques_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('salesTechnique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='agentmvp.salestechnique')),
            ],
        ),
    ]
